# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweeter', '0002_auto_20171217_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='hashtag',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
